### ISSUE TITLE
MOH 731 Section 1,2,4,5 & 6 Missing in the Template

### ISSUE THREAD

**Issue by mkaburu** [chap-uzima/IQTools#1]
Update the template to include all the missing section as they appear in the physical template. The data in IQCare can auto fill and leave blanks which will be filled manually. The sections too be in one sheet

**Comment by chris-githu** [comment]
Deployed in v3.9-beta1

**Comment by mkaburu** [comment]
@chris-githu The update is crushing changing the connection settings
![capturetyy](https://user-images.githubusercontent.com/31726479/33834201-459b49e8-de93-11e7-9eeb-ff0735eaf715.PNG)

**Comment by mkaburu** [comment]
@chris-githu  This is great. Would it be possible to pull this section from the ANC Module
![capturehei](https://user-images.githubusercontent.com/31726479/33941379-786890ec-e023-11e7-9748-3dbbc70962f0.PNG)

**Comment by chris-githu** [comment]
@mkaburu This is possible.
Let's discuss it for next year here #14

**Comment by mkaburu** [comment]
@chris-githu  Just realized when you run the new 731 indicator 2.2 is repeated twwice
![capture731](https://user-images.githubusercontent.com/31726479/44141734-ac2e346c-a086-11e8-8810-3e99eb214af5.JPG)
