### ISSUE TITLE
Differentiated Care Appointment Queries

### ISSUE THREAD

**Issue by thnesh** [chap-uzima/IQTools#10]
Now that differentiated care has picked up in most facilities, we need the queries for this added to the messaging queries.

**Comment by chris-githu** [comment]
@thnesh 
Please provide more information on this. Assume I have no/little idea what you are talking about :-)
- What are we trying to achieve?
- How/Where is the data being collected?
- Is it consistently collected?
- Do you already have a query designed that we can review?

Thanks.
