### ISSUE TITLE
Create tmp_IPT to track IPT treatment

### ISSUE THREAD

**Issue by chris-githu** [chap-uzima/IQTools#13]
We need to create a `tmp_IPT` table to enhance reporting and data mining for IPT which is continuously receiving a lot of requests.

Data Elements | Type | Source | Info
-- | -- | -- | --
PatientPK | INT | System | 
IPTStartDate | DATE | Pharmacy, Clinical Encounter | _TODO_
LastIPTDispense | DATE | Pharmacy | _TODO_
MonthsOnIPT | INT | Pharmacy | For DQA
Medication | STRING | Pharmacy | _TODO_
IPTOutcome | STRING | Clinical Encounter, Care End Form, _Assumed_ | _TODO_
DateOutcome | DATE| Clinical Encounter, Care End Form, _Assumed_ | _TODO_
DiscontinuationReason | STRING | Clinical Encounter | _TODO_

This will be used to address Issue #6

**Comment by chris-githu** [comment]
FYI @mkaburu @vogoti @thnesh 
This is available in v3.9-beta4 Please see how we can leverage on it to DQA IPT Outcomes #15

**Comment by vogoti** [comment]
Thanks for this @chris-githu is it possible to add tables to pick the following 1.Nutritional Assessment
2.Screening-Depression,GBV,Disclosure,CAGE & CRAFT
3.Adolescent Transitioning
4.Disclosure counselling
or can they be added as fields in the tmp_clinicalencounters table

**Comment by mkaburu** [comment]
@chris-githu what could cause tmp_ipt to return no results yet there are Isoniazid dispenses in the IQCare eg. Mbungoni db Link---https://www.dropbox.com/s/bsa3f6i9kmviwsb/IQCare-Deidentified-4.1.0%20St%20Martin%20Catholic%20Church%20Mbungoni2018-01-10.rar?dl=0

**Comment by chris-githu** [comment]
@mkaburu Mbungoni has classified INH under `Others` in `mst_Generic`. 
I'll adjust for this in tmp_Pharmacy in the next beta release.
Please keep an eye out for that.
Thanks.

**Comment by mkaburu** [comment]
@chris-githu  i will there are still some other sites that complain their IPT numbers are low.  i will check and give you an updated list.

**Comment by chris-githu** [comment]
I'll go ahead and close this for now.
We will continue to monitor this table along with DQA efforts for IPT treatment.
