### ISSUE TITLE
DQA | TB IPT Outcomes Documentation

### ISSUE THREAD

**Issue by chris-githu** [chap-uzima/IQTools#15]
Hi All.

We need to develop a strategy for IPT DQA. I noticed that a lot of pre (and post) IQCare v4.0 outcomes are missing. Most of these would show up as _Treatment Completed_ in reports.
- Let's determine what site staff will need to check for missing outcomes
- How they will update the records with the correct outcomes.

FYI @jmbula @lmwaniki @vogoti @mkaburu @thnesh

**Comment by jmbula** [comment]
@chris-githu  We will communicate to the facilities to update the outcomes, the clinical leads and TB Nurse will take up this task.

**Comment by mkaburu** [comment]
@chris-githu A tools was to be designed by palladium to help in updating IPT outcomes for patients who had completed IPT pre IQCarev4.0 since currently due to the system (IQCare v4.0) design you cannot have an outcome before an IPT start date and the IPT start date cannot be an earlier date than the current visit date

**Comment by jmbula** [comment]
@chris-githu @mkaburu   Yes,  I think  this would help for facilities to be able to update IPT outcomes for all patients retrospectively. This will sort the facilities using IQCare, the manual facilities will have to do this on the IPT register.

**Comment by chris-githu** [comment]
@mkaburu What tool? LOL!

**Comment by mkaburu** [comment]
@chris-githu  Wamathaga had shared it but it had issues https://www.dropbox.com/s/3sm9lfi5yb67q4n/IPTTool_1.0.exe?dl=0 i dont think the link is still valid. A better version was to be developed

**Comment by chris-githu** [comment]
@mkaburu Happy New Year!
If I'm understanding you correctly, we do not need anything developed in IQTools to assist in this.
The `IPTTool` app will resolve these DQA issues once updated.

Yes?

**Comment by mkaburu** [comment]
@chris-githu  Happy New Year
The IPTTool was to aid in documenting IPT outcomes for patients started IPT pre IQCare Version 4.0. The DQA is still needed to ensure we have the correct data.
