### ISSUE TITLE
Nutritional Assessment Table

### ISSUE THREAD

**Issue by vogoti** [chap-uzima/IQTools#17]
@chris-githu please assist create table in IQTools to capture nutritional assessment information;Height,Weight,BMI,Headcircumference, MUAC,Assessment(Normal,SAM,MAM,Overweight),assessment comments

**Comment by chris-githu** [comment]
@vogoti 
These would look like


Data Element | Comment
-- | --
PatientPK | REQUIRED
VisitDate | REQUIRED
Height | tmp_ClinicalEncounters
Weight | tmp_ClinicalEncounters
BMI | TODO
HeadCircumference | TODO
MUAC | TODO
NutritionAssessment | TODO
NutritionAssessmentComments | TODO

As we review the usability of `tmp_ClinicalEncounters`, we might want to consider creating a new table to house these elements, along with few others.

**Comment by chris-githu** [comment]
@vogoti Moving this, again, to v4.3. 👎
