### ISSUE TITLE
Family Information Table 

### ISSUE THREAD

**Issue by mkaburu** [chap-uzima/IQTools#19]
@chris-githu please assist to investigate why the PatientID and the Contact PatientID are the same for patients who have been linked via family information form. Attached is
![family info](https://user-images.githubusercontent.com/31726479/35323867-165eb946-0100-11e8-89cd-da18c0c0537b.PNG)
 a sample form the mater DB

**Comment by chris-githu** [comment]
@mkaburu 
Please check the `dtl_FamilyInfo` table in IQCare. `Ptn_Pk` vs. `ReferenceId`... are they the same for the examples above?

**Comment by mkaburu** [comment]
@chris-githu they seem to be the same
![capturej](https://user-images.githubusercontent.com/31726479/35330294-10f626ec-0114-11e8-81c8-3374cd9f1297.PNG)

**Comment by chris-githu** [comment]
Ok...this might be a bug in IQCare.
Please try and create a new family info linkage and see the result in the table.
Test with newly created patients so as not to mix up with previous records.

**Comment by mkaburu** [comment]
@chris-githu  Its different for a new patient that i have enrolled
![capturety](https://user-images.githubusercontent.com/31726479/35331214-801f1526-0117-11e8-91eb-c955742e6169.PNG)

**Comment by mkaburu** [comment]
@chris-githu Any progress on this issue?

**Comment by chris-githu** [comment]
HI @mkaburu 
This looks like a bug in IQCare.
 Please report it in the IQCare repository.
