### ISSUE TITLE
MOH 731 Line Lists | Nutrition and HIV

### ISSUE THREAD

**Issue by mkaburu** [chap-uzima/IQTools#2]
- Presumed TB- add any test conducted after the patient has been screened positive. Tests to include Gene-Xpert, and Sputum

- Nutrition and HIV- include a line list that dis-aggregates patients according Normal,SAM,MAM & Overweight and Obese

**Comment by chris-githu** [comment]
@mkaburu Please confirm that these are the results we are referring to.

@kenkirui 

Please confirm where the results are stored. Image below

![presumedtb](https://user-images.githubusercontent.com/13725334/33373315-5e815f04-d512-11e7-8e38-c3d75e35f88b.PNG)

**Comment by kenkirui** [comment]
@chris-githu The results are stored in [dtl_TBScreening] table. See query below that specifies the columns in the table:

select SputumSmear
, SputumSmearDate
, GeneExpert
, GeneExpertDate
, SputumDST
, SputumDSTDate
, ChestXRay
, ChestXRayDate
, TissueBiopsy
, TissueBiopsyDate
from [dtl_TBScreening]

**Comment by chris-githu** [comment]
@jmbula For the nutrition line list, would something like this suffice?


FacilityName | PatientID | AgeLastVisit | Gender | VisitDate | Assessment | StartARTDate
-- | -- | -- | -- | -- | -- | --
Chogoria (PCEA) Hospital | 0100 | 46.7 | Female | 9/4/2017 | Overweight | 11/5/2004
Chogoria (PCEA)   Hospital | 0105 | 51.3 | Female | 8/11/2017 | Overweight | 10/28/2004
Chogoria (PCEA) Hospital | 0020 | 38.8 | Male | 9/26/2017 | Normal | 9/9/2004
Chogoria (PCEA) Hospital | 0032 | 43.9 | Female | 8/28/2017 | Normal | 10/26/2004
Chogoria (PCEA)   Hospital | 0034 | 37.7 | Female | 8/31/2017 | Moderate Acute Malnutrition | 12/4/2004

**Comment by jmbula** [comment]
Hi Chris, Yes the variables  pulled are good , may be the only thing I could recommend to be added would be information on whether  a referral for nutritionist review/ intervention was done or not.

**Comment by chris-githu** [comment]
@mkaburu Please test this when you get a chance.
Thanks.

**Comment by mkaburu** [comment]
@chris-githu The line list is fine. I was using the Tumutumu DB for testing and the total number of patients on care is 1846 (ART + PreART), number with nutrition assessment is 1591 would the difference mean that those patients did not have nutrition assessment?

**Comment by chris-githu** [comment]
@mkaburu I guess so. Remember Nutrition Assessment relies on IQCare v4.0+. 
Depending on when you started using this version, you may have some clients who are active, but don't have a `Clinical Encounter` form.

I'll  go ahead and close this issue for now. If we find that there's a different problem with the number difference then please go ahead and open another issue specific to that.

Thanks.
