### ISSUE TITLE
ART Register Update

### ISSUE THREAD

**Issue by chris-githu** [chap-uzima/IQTools#20]
Based on new tools, we are updating the ART register.
Enhancements include
- Key Populations identification at ART Start
- Addition of Viral Load follow up at 6 monthly intervals.
Please see draft template for IQTools below
[ART_Register_Template.xlsx](https://github.com/chap-uzima/IQTools/files/1662768/ART_Register_Template.xlsx)

**Comment by chris-githu** [comment]
@vogoti @mkaburu @thnesh 
Please test this in v3.9.5

Let me know who else can assist with testing

**Comment by mkaburu** [comment]
@chris-githu the register is populating well. There are some patients however whom the regimen code is not displaying  but rather its the regime itself. Also some patients do not have weight under status at ART start could it be on the date they started ART no weight was documented?
![art re](https://user-images.githubusercontent.com/31726479/35666275-73e0b4bc-073a-11e8-8bb3-0ca27154ba98.PNG)

**Comment by thnesh** [comment]
@chris-githu some regimens in the ART register don't have regimen code e.g 3TC+DTG+TDF but on the FMAPS linelist they appear to have one which is wrong AF2B

**Comment by chris-githu** [comment]
Hi All.

Since this update was specific to VL follow up, we will deploy it as is for now. 
The regimen code issues will be tracked as independent issues.

@mkaburu @thnesh Please discuss internally and create a new issue(s) to as per the comments above.

Thanks.
