### ISSUE TITLE
Improving Viral Load data documentation in IQcare

### ISSUE THREAD

**Issue by jmbula** [chap-uzima/IQTools#21]
We are having a lot of issues with our Viral load data- from uptake of services to those eligible,  lack of  documentation of results , unreliable data for calculation of suppression rates  the list of  issues long...
I would like us to think of strategies that we can put in place to improve the accuracy and completeness of our VL data. Any ideas are welcome. @irenefaith @chris-githu @kenkirui @thnesh @mkaburu @snyachae @jkarigi @pgitonga @aoyugi @dkemunto

**Comment by jmbula** [comment]
@vogoti

**Comment by dkemunto** [comment]
Joyce,I concur with your concerns.As a program,we will need to do a process analysis and see how the VL results are received at the facility and how they enter into the system.In some facilities this process is hazy and when left to M and E,they will obviously prioritize other reports before entering VL data into the system.
At system level,is it possible to have a prompt/reminder alerting the clinician at the current visit that a VL had been done at the last visit and the results need to be entered into the system?

**Comment by dkemunto** [comment]
@chris-githu respond to my question above on system level.

**Comment by chris-githu** [comment]
@dkemunto @jmbula 
Yes, we can add an alert for a missing VL result. 
However, additional measures need to be taken to ensure that this is actually documented.

A monthly VL uptake report would serve as a continuous evaluation..... 
We also need to define whose responsibility it is (site-level) to ensure these records are in IQCare.

**Comment by chris-githu** [comment]
@mkaburu @vogoti @thnesh 
Based on discussions last week, would it be possible to split this issue into multiple action points?
I'm thinking we need to look at
- IQCare enhancements - different issue for each idea.. pre and post VL eligibility alerts?
- IQTools reports
 - 3PM
 - Eligibility Identification lists
 - Additional performance monitoring lists
 - Additional CQI reports

We can move this to the team discussions if necessary.

P.S. I'll close this here for now. Let's discuss and create specific actions as described above.

Thanks.
