### ISSUE TITLE
Patient appointment reminder through the SMS system

### ISSUE THREAD

**Issue by ekibunyi** [chap-uzima/IQTools#22]
@DMasese @irenefaith a while back there were plans to roll out SMS reminders to improve our retention and patinet outcomes. what is the progress in this? i am particularly interested in how this system can work for the pmtct population in regards EID and VL uptake as well as general patient appointment keeping.

**Comment by mkaburu** [comment]
@chris-githu on the same there is a query that pulls all clients who have consented to SMS, the query is refrencing a field named "SMSConsented" while in the table the field name is "ConsentedtoSMS"

**Comment by chris-githu** [comment]
@ekibunyi Was your question ever answered? 
@mkaburu Please open a new issue, not sure which query we are referring to.

Thanks.

**Comment by ekibunyi** [comment]
@chris-githu it was in reference to use of sms system for appointment management and patient reminders
