### ISSUE TITLE
CDC CT Report. LDL results are not a subset of <1000

### ISSUE THREAD

**Issue by chris-githu** [chap-uzima/IQTools#23]
From #7 

*@thnesh The <LDL is not a subset of <1000 in the Care & treatment report. <1000 is any result with a figure/number below 1000 but not <LDL.*

@vogoti Please verify this for documentation.

**Comment by chris-githu** [comment]
Applied in v4.0.0.4

**Comment by chris-githu** [comment]
@jmbula 
I got a call from our KARP partners about this.
They have asked CDC and apparently LDL should be included in numbers of Viral load < 1000cp/ml
- Viral Load Results less than 1000 = Undetectable + Detected under 1000 cp/ml

Please confirm with your CDC contacts again.

**Comment by jmbula** [comment]
@Chris, I will up with @Irene and get back.

**Comment by jmbula** [comment]
@Chris, I will up with @Irene and get back.

**Comment by chris-githu** [comment]
@jmbula @irenefaith Any feedback on this?

**Comment by irenefaith** [comment]
@chris-githu , @jmbula it's also CDC than gave us the guidance that in care and treatment report ,*The <LDL is not a subset of <1000 in the Care & treatment report. <1000 is any result with a figure/number below 1000 but not <LDL** ,today am with CDC and they are also not clear about it and they would want to do further consultation .Kindly let me give feedback next week.

**Comment by chris-githu** [comment]
@irenefaith Ok. Let's wait for confirmation.

**Comment by chris-githu** [comment]
@irenefaith Any feedback on this?
