### ISSUE TITLE
tmp_ViralLoads

### ISSUE THREAD

**Issue by chris-githu** [chap-uzima/IQTools#25]
Due to the importance of this lab test, and the fact that results do not fit in to the `tmp_Labs` format, we will be creating a special table `tmp_ViralLoads` in IQTools to capture the following data elements

Data Element | Type | Expected   Values
-- | -- | --
PatientPK | INT | IQCare   system Ptn_Pk
DateOrdered | DATE | as per system date format
Justification | TEXT | Routine,   Targeted(….)
DateReported | DATE | as per system date format
VLResultText | TEXT | Sample   Rejected, Pending, Missing, Undetectable, Detectable…
VLResultValue | INT | Actual copies/ml

We may expand this to capture the VLs period classification if possible.

**Comment by vogoti** [comment]
Great Idea @chris-githu

**Comment by chris-githu** [comment]
Partly done. Will review in v4.3

Data Element | Type | Expected   Values
-- | -- | --
PatientPK | INT | IQCare   system Ptn_Pk
DateOrdered | DATE | as per system date format
DateReported | DATE | as per system date format
VLResult | INT | Actual copies/ml, 0 if undetectable, empty if no result yet
