### ISSUE TITLE
Line list for genexpert test for presumed TB

### ISSUE THREAD

**Issue by jmbula** [chap-uzima/IQTools#3]
Hi @chris would you kindly add a line list function for patients with presumed TB who get genexpert test done within the month.

**Comment by chris-githu** [comment]
Let's merge this with Issue #2

**Comment by chris-githu** [comment]
@jmbula Please note that the guideline for this indicator is to count only those presumed to have TB within the reporting month. This is different from the screening indicator which checks for TB screening at last visit.
This is now available for testing @mkaburu

**Comment by jmbula** [comment]
@chris-githu great  and thanks. Once its tested i will give you our feedback if it will sort out the required report on gene xpert utilization or not.

**Comment by mkaburu** [comment]
@chris-githu The line list is OK. There are some sites that don't fill genexpert as a lab but rather use the fields in the clinical encounter form @jmbula what would be the ideal the source for this indicator?

**Comment by jmbula** [comment]
@mkaburu Ideally for all gene expert tests a lab request form should be raised (whether manual or via IQCare), this information should be  filled-in in the presumptive TB register (the manual one or the one in IQcare TB module) and then results should be updated in the lab module and the patient level records be updated in the patient encounter. So for facilities that go straight to use the clinical encounter for gene expert line list- the results can only be accurate if the patient encounter is ALWAYS up to date. For most facilities this is not the case so the most ideal source would be the PRESUMPTIVE TB REGISTER- relying on the hope that its also consistently filled every time when a gene expert test is ordered and results consistently updated on the same.

**Comment by chris-githu** [comment]
@mkaburu @jmbula, For this line list, we are using the `Clinical Encounter` data as shown in the screen shot below. I would expect that these results should end up here for consistency. Please follow up with the rest of the team to find out how the sites are documenting these results in IQCare.

![tb testing](https://user-images.githubusercontent.com/13725334/33981989-fc99f486-e0bf-11e7-996a-eb602ed94dc6.PNG)

Thanks.

**Comment by chris-githu** [comment]
This has been deployed to v4.
