### ISSUE TITLE
Query on GBV

### ISSUE THREAD

**Issue by ekibunyi** [chap-uzima/IQTools#31]
@chris-githu @irenefaith @lmwaniki @aoyugi can we have the screening questions for GBV incorporated into IQ care as it is part of patient care which cuts across PMTCT, adolescents and adult care? the questions from the guidelines are as below:
1. Within the past year, have you been hit, slapped, kicked, or physically hurt by someone in any way? 
2. Are you in a relationship with a person who physically hurts you? 
3. Are you in a relationship with a person who threatens, frightens, insults you, or treats you badly? 
4. Are you in a relationship with a person who forces you to participate in sexual activities that make you feel uncomfortable?
 5. Have you ever experienced any of the above with someone you do not have a relationship with?”

**Comment by mkaburu** [comment]
@ekibunyi The questions already exist in IQCARE
![capturetyyyyyy](https://user-images.githubusercontent.com/31726479/39526822-a48ac834-4e28-11e8-908f-b7ddc9e2c1c3.PNG)

**Comment by ekibunyi** [comment]
@mkaburu great! are we able to run queries and get data as required e.g number of cases in pmtct assessed for GBV and intervened?

**Comment by mkaburu** [comment]
@chris-githu Please help with the queries

**Comment by mkaburu** [comment]
@ekibunyi Please be specific on the queries you would want

**Comment by irenefaith** [comment]
@chris-githu ,@mkaburu, i propose we get queries to first determine if the questions as indicated by  @ekibunyi  are being asked

**Comment by chris-githu** [comment]
@mkaburu Following up with this. Any luck?

**Comment by mkaburu** [comment]
@chris-githu This is what i have been able to pull using the attached query. The data is from Jan-march 2018
[GBV Data.xlsx](https://github.com/chap-uzima/IQTools/files/2030722/GBV.Data.xlsx)
[SGBV.txt](https://github.com/chap-uzima/IQTools/files/2030723/SGBV.txt)

**Comment by chris-githu** [comment]
@vogoti 
Is this related to the the email you sent on IQCare assessments?
FYI @mkaburu

**Comment by ekibunyi** [comment]
@vogoti @mkaburu  we can close  this as resolved if we are able to get reports in line with GBV and OVC.

**Comment by ekibunyi** [comment]
@mkaburu just before we resolve, do we have a next step in IQ care that gives guidance for intervention and documentation for the client with a positive screen i.e has a yes to either of the five GBV questions?
