### ISSUE TITLE
TX_NET_NEW

### ISSUE THREAD

**Issue by chris-githu** [chap-uzima/IQTools#33]
Hi @irenefaith @vogoti @mkaburu @lmwaniki 

Just from a meeting with CDC/HMIS. Are you aware of this tool by CDC to report on `TX_NET_NEW`?

**Comment by chris-githu** [comment]
It's a big document but this is the site level worksheet
[TX_NET_NEW Site Level.xlsx](https://github.com/chap-uzima/IQTools/files/2007725/TX_NET_NEW.Site.Level.xlsx)

FYI @jmbula @dkemunto @thnesh

**Comment by jmbula** [comment]
@chris-githu 
Thanks Chris for sharing I don't think I have seen this before, let me go through and give  my comments later.

**Comment by irenefaith** [comment]
@chris-githu 
I am seeing this tool for the first time.
Is it rolled out yet?Are you incorporating it in Iqtools?

**Comment by chris-githu** [comment]
@vogoti 

As discussed, let's anticipate this request at the end of Q3.
To begin, please extract from DATIM PIVOT our TX_CURR from EMR sites as of Q2.

FYI @mkaburu, @thnesh , @lmwaniki @irenefaith

**Comment by lmwaniki** [comment]
[TX_CUrr.xlsx](https://github.com/chap-uzima/IQTools/files/2136477/TX_CUrr.xlsx)
@chris-githu -TX curr end of Q2..I have included non EMR sites coz we also need to account for their net new

**Comment by chris-githu** [comment]
@lmwaniki 
Thanks for this.
@vogoti @mkaburu @thnesh @irenefaith 

Please see attached comparison with IQCare DBs for Q2
[TX_CURR_Q2.xlsx](https://github.com/chap-uzima/IQTools/files/2136951/TX_CURR_Q2.xlsx)

- Total DATIM = 44,594
- Total IQCare = 44,594 
  - This is very impressive!
  - +1 in Karura and -1 in Maua evens the total out. 
- Line list of the 44,594 clients.
  - This will serve as a starting point for TX_NET_NEW calculations at the end of this quarter. Keep this file in a safe place! Call me for the password.

**Comment by chris-githu** [comment]
This issue was moved to chap-uzima/DataWarehouse#11
