### ISSUE TITLE
MOH 731 Currently on ART - Below 1 year 

### ISSUE THREAD

**Issue by mkaburu** [chap-uzima/IQTools#34]
@chris-githu what would cause Currently on ART - Below 1 year  not populate in 731 but in the C&T report populate?
![image](https://user-images.githubusercontent.com/31726479/40294835-dd07f310-5cdf-11e8-828c-2c482dc5fdb2.png)

**Comment by chris-githu** [comment]
@mkaburu 
Good catch!
This was due to an excel mapping issue. Look out for a fix in the next beta.

Thanks.

**Comment by chris-githu** [comment]
@mkaburu 
Please check whether this has been resolved in [v4.2.1-beta](http://iqtools.azurewebsites.net/apps/iqtools/beta/publish.htm)

**Comment by mkaburu** [comment]
@chris-githu This is resolved
