### ISSUE TITLE
Care & Treatment Report : Eligible

### ISSUE THREAD

**Issue by mkaburu** [chap-uzima/IQTools#35]
@chris-githu We have realized there is an issue on how data for this section is being pulled e.g. eligible for Month12 VL its picking clients who are on ART from 10 months. we think it should pick from exactly 12 months onwards so as not to inflate number eligible for VL
![captureeligi](https://user-images.githubusercontent.com/31726479/40477506-4a51b822-5f4f-11e8-9167-39e8b28e4029.PNG)

**Comment by chris-githu** [comment]
@mkaburu 
Are these clients who missed their m6 VL?
If so, would the #36 suggestion resolve this?

**Comment by mkaburu** [comment]
@chris-githu not necessarily. the query was looking at the startART date and the months on ART these patients would not be eligible for 12 month VL. Can we say that for one to be eligible for 12month vl they must be on ART for 12 months?

**Comment by dkemunto** [comment]
Hi everyone.We had a discussion around this matter with Dr.Naibei and Dr.Janice yesterday.Here are our thoughts (I will illustrate with an example).

Patient x is started on ART on 1st/January/2017.The client will have done their 6 months on ART by 30th/June/2017.We expect the 6 month VL to be done in July 2017,the 12 month VL should be done in Jan 2018 then the annual VL in January every year after that.

@mkaburu yes.One can only be eligible for a 12 month VL if there have been on ART for 12 months.

The milestones are very distinct.We expect the 6 month VL to be done by the last day of the 7th month and we also expect that the 12th month VL should have been done by the last day of the 13th month.If those milestones are missed,we agreed that they have been missed and we should not 'compensate' for the facilities laxity.Missing the VL milestones will then become a CQI priority for the affected sites. @JaniceKM @knaibei @vogoti @jmbula
