### ISSUE TITLE
Care & Treatment Program report: Eligible for VL line list

### ISSUE THREAD

**Issue by mkaburu** [chap-uzima/IQTools#36]
@chris-githu @vogoti Can add the eligibility reasons for month 6 and 12 to be like this:

- Month 6 -  On ART for 6 months as of the reporting month
- Month 6 (Missed Month 6VL) -  these are patients who missed their 6 month VL  and are between month 7 and 11 on ART.
- Month 12 -  On ART for 12 months as of the reporting month and month 6 was suppressed.
- Month 12 (Missed Month 12 VL) -  these are patients who missed their 12 month VL  and are on between month 13 and 18 on ART.
- The other eligibility reasons are OK.

**Comment by mkaburu** [comment]
@chris-githu Kindly also consider adding the LastVLDate in this list where applicable

**Comment by chris-githu** [comment]
@mkaburu I'm in agreement with this.
Have you discussed it with @jmbula? Others?

**Comment by mkaburu** [comment]
@chris-githu the initial discussion was with @vogoti but am hoping @jmbula  and others can share their views here but will follow up

**Comment by dkemunto** [comment]
@mkaburu I still do not understand how you came up with such a wide 'grace period'If a client misses a milestone,they have essentially missed it.e.g.Going back to the example I gave earlier of a client who started ART on 1st/Jan/2017,if by 31st/July/2017 we do not have a VL,then the 6 month VL milestone is past.A VL can be done between month 8 and month 11 but this is not really the 6 month VL.Give it any other name-(not too sure what).

Please let us pick the discussion from there.

**Comment by ekibunyi** [comment]
@mkaburu I agree with Diana. we need to keep the time lines short and have a way of flagging them and not wait for that long a time line. remember for all PMTCT clients it should be every 6 months.
