### ISSUE TITLE
MoH 731 - TB Screening

### ISSUE THREAD

**Issue by aoyugi** [chap-uzima/IQTools#4]
TB Screening data in MoH731 is the data picking patients on ART or even Pre-ART patients?

**Comment by chris-githu** [comment]
@aoyugi This query picks data for both ART and Pre-ART patients in both v1 & v2 versions of MoH 731.
Should we limit this to just ART patients?

**Comment by chris-githu** [comment]
@chap-uzima/reportsvalidation Please weigh in on this.

**Comment by thnesh** [comment]
@aoyugi @chris-githu. i think it should be retained as it is as per guidelines

![tb screening](https://user-images.githubusercontent.com/31725448/33373607-c6cbf596-d513-11e7-825e-c20daf4b81d5.jpg)

**Comment by chris-githu** [comment]
@aoyugi @thnesh Thanks.
I believe we can close this issue.
