### ISSUE TITLE
Appointments in Schedular not appearing in tmp_ClinicalEncounters

### ISSUE THREAD

**Issue by chris-githu** [chap-uzima/IQTools#40]
Update `tmp_ClinicalEncounters` to capture Appointments from all sources and not just encounter forms.

FYI @mkaburu

**Comment by chris-githu** [comment]
@mkaburu Please test this in v4.2.3-beta

**Comment by mkaburu** [comment]
@chris-githu If you add the next appointment date should it appear in tmp_clinicalencounters ?
![scheduler](https://user-images.githubusercontent.com/31726479/41910869-9fae0fbe-7953-11e8-8c8f-8ddc8c60c252.JPG)
![app](https://user-images.githubusercontent.com/31726479/41910875-a34d9c98-7953-11e8-98f7-e6545cf1d635.JPG)
from the example above i have added a new appointment which has updated in dtl_patientappointment.

**Comment by chris-githu** [comment]
Is there a visit on the same day that you created the appointment in schedular?

**Comment by mkaburu** [comment]
@chris-githu  Mostly you have just a pharmacy form

**Comment by chris-githu** [comment]
@mkaburu 
The clinical encounters table is really designed for visits where the patient actually visited the facility.
Even treatment buddy visits shouldn't be here(they currently are). 
Introducing pharmacy only visits will only aggravate the issue.
For instance, how do we determine TB screening at last visit if we have pharmacy only and treatment buddy visits?

I'm thinking that we might have to move appointment dates out of tmp_ClinicalEncounters.
We can have a `tmp_PatientAppointments` table for this

FYI @vogoti @thnesh
