### ISSUE TITLE
HEI Register

### ISSUE THREAD

**Issue by chris-githu** [chap-uzima/IQTools#5]
@jmbula @aoyugi 
Please respond to this with a soft copy of the new HEI Register

**Comment by aoyugi** [comment]
[Register - HIV Exposed Infant _Final_August 31.xlsx](https://github.com/chap-uzima/IQTools/files/1513780/Register.-.HIV.Exposed.Infant._Final_Aug
Here is the latest version of the HEI register

**Comment by thnesh** [comment]
@aoyugi @jmbula Is the HEI register that incorporates the 9mnth and 12 mnth PCR not out yet. This one seems to have the 9 month antibody test that is no longer being done

**Comment by chris-githu** [comment]
@thnesh Please send the new HEI Register

**Comment by thnesh** [comment]
@chris-githu, Here's the new HEI register
[HIV Exposed Infant Register  for print 03_11_2016.xlsx](https://github.com/chap-uzima/IQTools/files/1517290/HIV.Exposed.Infant.Register.for.print.03_11_2016.xlsx)

**Comment by thnesh** [comment]
@chris-githu New HEI resister not effected. Timeline??

**Comment by thnesh** [comment]
[HIV Exposed Infant Register  for print 03_11_2016.xlsx](https://github.com/chap-uzima/IQTools/files/1684584/HIV.Exposed.Infant.Register.for.print.03_11_2016.xlsx)

**Comment by chris-githu** [comment]
@thnesh 
We are changing this to Milestone 4.1 due on Feb 28th.

Thanks.

**Comment by chris-githu** [comment]
OBE
