### ISSUE TITLE
Pharmacy Reports 

### ISSUE THREAD

**Issue by Muchina-David** [chap-uzima/IQTools#52]
@chris-githu I kindly wish to know whether the reporting component of the Pharmacy Module has been finalized i.e. system generated FCDRR and FMAPS reports.

**Comment by chris-githu** [comment]
@Muchina-David @mkaburu @vogoti 
FMAPs and CDRR reports have been published with IQTools 5.0.1.2
Please test and revert.

I will go ahead and close this issue.
Please open problem-specific issues if you encounter any.
