### ISSUE TITLE
VL Cascade Report/Dataset

### ISSUE THREAD

**Issue by chris-githu** [chap-uzima/IQTools#8]
From the CQI Template discussions, we need to design a Viral Load cascade report in IQTools.

**Viral Load Uptake at 6 months**
Number Started on ART 6 months ago
Number with VL at the end of 6 months
Number Suppresed
Suppression %
**Viral Load Uptake at 12 months**
Number on ART for more than 12  months
Number with VL in the last 12 months
Number Suppresed
Suppression %
**Viral Load Cascade**
1st VL >1000
_1st EAC done_
_2nd EAC done_
_3rd EAC done_
_MDT discussion done_
2nd VL Recorded
2nd VL >1000
Started 2nd Line ART

@chap-uzima/reportsvalidation Please review this.

**Comment by jmbula** [comment]
@chris-githu  kindly find attached the updated template for all the CQI Reports including the VL cascade for you to assist with putting them as part of reports that can be generated through IQtools as we havd discussed. We organized the different reports into tabs as you had advised.
[Comprehensive CQI Reporting Template.xlsx](https://github.com/chap-uzima/IQTools/files/1547879/Comprehensive.CQI.Reporting.Template.xlsx)

**Comment by chris-githu** [comment]
Hi @jmbula Thanks for this.

The Viral Load _Cascade_ / _Monitoring_ theme appears in very many places.
A few of these are 
- VL Cascade _CQI Tool_ 
- The Care & Treatment Report #7 
- Pediatric QoC Report #9 
- PMTCT VL Cascade _CQI Tool_

The theme is the same
- Who's active on treatment? 
- Who has been retained at 12months?
- Who's eligible for VL testing?
- Who was tested?
- Who is suppressed/or not?
- Enhanced Counselling
- Repeat Testing
- Still not suppressed
- Switched to Second Line

Minor differences are to do with the 
- Focus group (Peds/Adolescents/PMTCT...)
- Analysis period (Monthly vs. Quarterly)

Would it be possible to collapse these into one `VL Report` or `VL Dataset` that the sites can generate and we can use to populate either of these requirements?

Let's take some time to discuss this so that we don't end up designing multiple solutions that all address the same issue.

FYI @mkaburu @vogoti @aoyugi @lmwaniki @irenefaith

**Comment by vogoti** [comment]
Hi @chris-githu is it possible to please provide us queries that we can use to generate data for the CQI reporting template before it is incorporated into IQTools
FYI @pgitonga

**Comment by chris-githu** [comment]
OBE
